In [77]:
import sys
sys.path.insert(0, "/Users/hugofayolle/Desktop/Bourse/Bourse_test/")
from Model.codes import Codes
from Model.constants import API_KEY, ENVIRONMENT
from Model.env import Env
from Model.file import File
from Model.functions import Function
from Model.indicator import Indicator
from Model.stock import Stock
from Model.strategy import Strategy
from functools import partial
from itertools import product
import datetime
import Model.exploration as e
import itertools
import quandl
import dill as pickle
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
quandl.ApiConfig.api_key = API_KEY # mandatory to make api calls on quandl
print(ENVIRONMENT)

Environment: DEV

# Definition of Stock

In [58]:
orange = Stock('ORA')

In [59]:
orange

Stock : ORA (DEV)

In [60]:
orange.get_attributes()

name : ORA
type : Stock
env : Environment: DEV
filename : Development/Stock/ORA.p
folder : /Users/hugofayolle/Desktop/Bourse/Bourse_test/Data/
path : /Users/hugofayolle/Desktop/Bourse/Bourse_test/Data/Development/Stock/ORA.p
creation_date : 2018-09-29 10:31:04
last_update : 2018-09-29 10:31:04
data : Empty DataFrame
Columns: []
Index: []
code : ORA
full_code : EURONEXT/ORA
full_name : Orange (ORA)
description : Stock Prices for Orange from the Euronext Stock Exchange. Currency: EUR. Market: Euronext Paris
first_date : 2014-02-14 00:00:00
include_in_analysis : True
indicators : []
strategies : []
last_date : None

# Stock refresh

In [61]:
orange.refresh(to_date= '2015-07-13')

ORA successfully updated!

In [62]:
orange.get_attributes()

name : ORA
type : Stock
env : Environment: DEV
filename : Development/Stock/ORA.p
folder : /Users/hugofayolle/Desktop/Bourse/Bourse_test/Data/
path : /Users/hugofayolle/Desktop/Bourse/Bourse_test/Data/Development/Stock/ORA.p
creation_date : 2018-09-29 10:31:04
last_update : 2018-09-29 10:31:06
data :               OPEN    HIGH     LOW   CLOSE      VOLUME      TURNOVER
DATE
2014-02-14   9.200   9.237   9.143   9.231   5493685.0  5.056534e+07
2014-02-17   9.215   9.269   9.184   9.226   4143547.0  3.824005e+07
2014-02-18   9.224   9.321   9.221   9.303   8540213.0  7.937708e+07
2014-02-19   9.276   9.364   9.269   9.340   6594004.0  6.152310e+07
2014-02-20   9.250   9.384   9.233   9.384   6025974.0  5.633642e+07
2014-02-21   9.403   9.487   9.345   9.434   8894573.0  8.386507e+07
2014-02-24   9.378   9.648   9.373   9.613   8150488.0  7.792999e+07
2014-02-25   9.550   9.690   9.440   9.630   9295776.0  8.895996e+07
2014-02-26   9.603   9.623   9.252   9.305  18152477.0  1.703480e+08
2014-02-27   9.300   9.327   9.101   9.200  12172862.0  1.119747e+08
2014-02-28   9.173   9.200   9.030   9.069  14416002.0  1.309492e+08
2014-03-05   9.074   9.298   9.020   9.165  10647930.0  9.781073e+07
2014-03-06   9.500  10.235   9.440  10.130  47855850.0  4.753191e+08
2014-03-07  10.140  10.500  10.060  10.235  26751172.0  2.752481e+08
2014-03-10  10.240  10.715  10.240  10.675  20255363.0  2.144326e+08
2014-03-11  10.650  10.665  10.460  10.595  12841397.0  1.359032e+08
2014-03-12  10.505  10.585  10.455  10.555  10823248.0  1.138331e+08
2014-03-13  10.560  10.590  10.260  10.300   9396474.0  9.762179e+07
2014-03-14  10.165  10.205   9.700  10.115  23505993.0  2.360043e+08
2014-03-17  10.050  10.180   9.943  10.180   8212576.0  8.309310e+07
2014-03-18  10.090  10.330  10.020  10.205   8165304.0  8.334342e+07
2014-03-19  10.200  10.200  10.060  10.145   8132717.0  8.251049e+07
2014-03-20  10.030  10.250   9.922  10.220  15257210.0  1.538642e+08
2014-03-21  10.260  10.360  10.220  10.225  17777684.0  1.823607e+08
2014-03-24  10.180  10.295   9.992  10.030   8116514.0  8.183445e+07
2014-03-25  10.020  10.260   9.970  10.225   8704683.0  8.866937e+07
2014-03-26  10.260  10.380  10.225  10.270   6136637.0  6.312681e+07
2014-03-27  10.265  10.435  10.195  10.435   9100609.0  9.450509e+07
2014-03-28  10.490  10.725  10.480  10.710   9185692.0  9.796793e+07
2014-03-31  10.705  10.765  10.580  10.720   6968061.0  7.454900e+07
...            ...     ...     ...     ...         ...           ...
2015-05-18  14.280  14.760  14.190  14.740  10990949.0  1.598446e+08
2015-05-19  14.785  14.935  14.765  14.865  11461734.0  1.702722e+08
2015-05-20  14.630  14.845  14.530  14.835   9567697.0  1.407291e+08
2015-05-21  14.820  14.930  14.760  14.830   4892179.0  7.249802e+07
2015-05-22  14.750  14.750  14.455  14.600   9403464.0  1.369677e+08
2015-05-25  14.580  14.580  14.380  14.470   1425383.0  2.059971e+07
2015-05-26  14.535  14.750  14.440  14.505   6434151.0  9.368562e+07
2015-05-27  14.630  14.770  14.450  14.735   8020099.0  1.171406e+08
2015-05-28  14.630  14.850  14.565  14.685   4488386.0  6.605881e+07
2015-05-29  14.675  14.745  14.320  14.360   9093974.0  1.315679e+08
2015-06-01  14.460  14.730  14.310  14.550   9040711.0  1.314196e+08
2015-06-02  14.595  14.800  14.405  14.635   8294907.0  1.215092e+08
2015-06-03  14.630  14.845  14.565  14.600   7188987.0  1.053358e+08
2015-06-04  14.535  14.715  14.275  14.505   8377360.0  1.211513e+08
2015-06-05  14.380  14.460  14.200  14.260   7792959.0  1.113541e+08
2015-06-08  13.915  13.965  13.630  13.630  10255743.0  1.412499e+08
2015-06-09  13.640  13.715  13.295  13.555  10680205.0  1.441263e+08
2015-06-10  13.460  13.900  13.300  13.825  10599715.0  1.450180e+08
2015-06-26  14.500  14.805  14.395  14.670   8652391.0  1.264544e+08
2015-06-29  14.055  14.350  13.960  14.055  12766388.0  1.807619e+08
2015-06-30  13.980  14.175  13.810  13.810  12032235.0  1.679855e+08
2015-07-01  13.940  14.260  13.855  14.080  10804641.0  1.523141e+08
2015-07-02  14.140  14.290  14.085  14.160   8154936.0  1.156540e+08
2015-07-03  14.190  14.360  14.040  14.085   8315443.0  1.179216e+08
2015-07-06  13.810  14.010  13.605  13.655   8650428.0  1.190343e+08
2015-07-07  13.670  13.785  13.250  13.250  10678298.0  1.435822e+08
2015-07-08  13.220  13.470  13.200  13.365  11519077.0  1.537186e+08
2015-07-09  13.440  13.705  13.360  13.655   9765522.0  1.326167e+08
2015-07-10  14.000  14.365  13.850  14.325  12903451.0  1.829831e+08
2015-07-13  14.610  14.700  14.390  14.640   9412289.0  1.373634e+08

[331 rows x 6 columns]
code : ORA
full_code : EURONEXT/ORA
full_name : Orange (ORA)
description : Stock Prices for Orange from the Euronext Stock Exchange. Currency: EUR. Market: Euronext Paris
first_date : 2014-02-14 00:00:00
include_in_analysis : True
indicators : []
strategies : []
last_date : 2015-07-13 00:00:00

# Definition of Function

In [63]:
def SMA(df, window, column = 'CLOSE'):
    return df[column].rolling(window = window).mean()

In [64]:
SMA = Function('SMA', SMA)

In [65]:
SMA.get_attributes()

name : SMA
type : Function
env : Environment: DEV
filename : Development/Function/SMA.p
folder : /Users/hugofayolle/Desktop/Bourse/Bourse_test/Data/
path : /Users/hugofayolle/Desktop/Bourse/Bourse_test/Data/Development/Function/SMA.p
creation_date : 2018-09-29 10:31:06
last_update : 2018-09-29 10:31:06
execute : <function SMA at 0x1113709d8>

# Definition of Indicator

In [66]:
from functools import partial

In [67]:
SMA20 = Indicator('SMA20', partial(SMA.execute, window = 20))
SMA50 = Indicator('SMA50', partial(SMA.execute, window = 50))
SMA80 = Indicator('SMA80', partial(SMA.execute, window = 80))
SMA150 = Indicator('SMA150', partial(SMA.execute, window = 150))

In [68]:
SMA20.get_attributes()

name : SMA20
type : Indicator
env : Environment: DEV
filename : Development/Indicator/SMA20.p
folder : /Users/hugofayolle/Desktop/Bourse/Bourse_test/Data/
path : /Users/hugofayolle/Desktop/Bourse/Bourse_test/Data/Development/Indicator/SMA20.p
creation_date : 2018-09-29 10:31:06
last_update : 2018-09-29 10:31:06
history : {}
compute : functools.partial(<function SMA at 0x1113709d8>, window=20)

# Application of Indicator

In [69]:
orange.add_indicator('SMA80')
orange.add_indicator('SMA150')

In [70]:
orange.indicators

['SMA80', 'SMA150']

In [71]:
orange.data

,OPEN,HIGH,LOW,CLOSE,VOLUME,TURNOVER,SMA80,SMA150
DATE,,,,,,,,
2014-02-14,9.200,9.237,9.143,9.231,5493685.0,5.056534e+07,NaN,NaN
2014-02-17,9.215,9.269,9.184,9.226,4143547.0,3.824005e+07,NaN,NaN
2014-02-18,9.224,9.321,9.221,9.303,8540213.0,7.937708e+07,NaN,NaN
2014-02-19,9.276,9.364,9.269,9.340,6594004.0,6.152310e+07,NaN,NaN
2014-02-20,9.250,9.384,9.233,9.384,6025974.0,5.633642e+07,NaN,NaN
2014-02-21,9.403,9.487,9.345,9.434,8894573.0,8.386507e+07,NaN,NaN
2014-02-24,9.378,9.648,9.373,9.613,8150488.0,7.792999e+07,NaN,NaN
2014-02-25,9.550,9.690,9.440,9.630,9295776.0,8.895996e+07,NaN,NaN
2014-02-26,9.603,9.623,9.252,9.305,18152477.0,1.703480e+08,NaN,NaN
2014-02-27,9.300,9.327,9.101,9.200,12172862.0,1.119747e+08,NaN,NaN
2014-02-28,9.173,9.200,9.030,9.069,14416002.0,1.309492e+08,NaN,NaN
2014-03-05,9.074,9.298,9.020,9.165,10647930.0,9.781073e+07,NaN,NaN
2014-03-06,9.500,10.235,9.440,10.130,47855850.0,4.753191e+08,NaN,NaN
2014-03-07,10.140,10.500,10.060,10.235,26751172.0,2.752481e+08,NaN,NaN
2014-03-10,10.240,10.715,10.240,10.675,20255363.0,2.144326e+08,NaN,NaN
2014-03-11,10.650,10.665,10.460,10.595,12841397.0,1.359032e+08,NaN,NaN
2014-03-12,10.505,10.585,10.455,10.555,10823248.0,1.138331e+08,NaN,NaN
2014-03-13,10.560,10.590,10.260,10.300,9396474.0,9.762179e+07,NaN,NaN
2014-03-14,10.165,10.205,9.700,10.115,23505993.0,2.360043e+08,NaN,NaN
2014-03-17,10.050,10.180,9.943,10.180,8212576.0,8.309310e+07,NaN,NaN
2014-03-18,10.090,10.330,10.020,10.205,8165304.0,8.334342e+07,NaN,NaN
2014-03-19,10.200,10.200,10.060,10.145,8132717.0,8.251049e+07,NaN,NaN
2014-03-20,10.030,10.250,9.922,10.220,15257210.0,1.538642e+08,NaN,NaN
2014-03-21,10.260,10.360,10.220,10.225,17777684.0,1.823607e+08,NaN,NaN
2014-03-24,10.180,10.295,9.992,10.030,8116514.0,8.183445e+07,NaN,NaN
2014-03-25,10.020,10.260,9.970,10.225,8704683.0,8.866937e+07,NaN,NaN
2014-03-26,10.260,10.380,10.225,10.270,6136637.0,6.312681e+07,NaN,NaN
2014-03-27,10.265,10.435,10.195,10.435,9100609.0,9.450509e+07,NaN,NaN
2014-03-28,10.490,10.725,10.480,10.710,9185692.0,9.796793e+07,NaN,NaN
2014-03-31,10.705,10.765,10.580,10.720,6968061.0,7.454900e+07,NaN,NaN
...,...,...,...,...,...,...,...,...
2015-05-18,14.280,14.760,14.190,14.740,10990949.0,1.598446e+08,15.419875,14.334767
2015-05-19,14.785,14.935,14.765,14.865,11461734.0,1.702722e+08,15.419188,14.357067
2015-05-20,14.630,14.845,14.530,14.835,9567697.0,1.407291e+08,15.413625,14.378900
2015-05-21,14.820,14.930,14.760,14.830,4892179.0,7.249802e+07,15.404438,14.400533
2015-05-22,14.750,14.750,14.455,14.600,9403464.0,1.369677e+08,15.389063,14.418500
2015-05-25,14.580,14.580,14.380,14.470,1425383.0,2.059971e+07,15.372063,14.438867
2015-05-26,14.535,14.750,14.440,14.505,6434151.0,9.368562e+07,15.355375,14.461333
2015-05-27,14.630,14.770,14.450,14.735,8020099.0,1.171406e+08,15.338375,14.484133
2015-05-28,14.630,14.850,14.565,14.685,4488386.0,6.605881e+07,15.326688,14.506767
2015-05-29,14.675,14.745,14.320,14.360,9093974.0,1.315679e+08,15.311188,14.528767
2015-06-01,14.460,14.730,14.310,14.550,9040711.0,1.314196e+08,15.293500,14.552133
2015-06-02,14.595,14.800,14.405,14.635,8294907.0,1.215092e+08,15.276063,14.577033
2015-06-03,14.630,14.845,14.565,14.600,7188987.0,1.053358e+08,15.260438,14.602333
2015-06-04,14.535,14.715,14.275,14.505,8377360.0,1.211513e+08,15.242125,14.626700
2015-06-05,14.380,14.460,14.200,14.260,7792959.0,1.113541e+08,15.225375,14.647233
2015-06-08,13.915,13.965,13.630,13.630,10255743.0,1.412499e+08,15.194813,14.666600
2015-06-09,13.640,13.715,13.295,13.555,10680205.0,1.441263e+08,15.164625,14.686833
2015-06-10,13.460,13.900,13.300,13.825,10599715.0,1.450180e+08,15.136125,14.708000
2015-06-26,14.500,14.805,14.395,14.670,8652391.0,1.264544e+08,15.117063,14.733800
2015-06-29,14.055,14.350,13.960,14.055,12766388.0,1.807619e+08,15.088438,14.745433
2015-06-30,13.980,14.175,13.810,13.810,12032235.0,1.679855e+08,15.060188,14.752800
2015-07-01,13.940,14.260,13.855,14.080,10804641.0,1.523141e+08,15.043250,14.762867
2015-07-02,14.140,14.290,14.085,14.160,8154936.0,1.156540e+08,15.022000,14.774833
2015-07-03,14.190,14.360,14.040,14.085,8315443.0,1.179216e+08,15.001875,14.785600
2015-07-06,13.810,14.010,13.605,13.655,8650428.0,1.190343e+08,14.973813,14.790033
2015-07-07,13.670,13.785,13.250,13.250,10678298.0,1.435822e+08,14.937813,14.793400
2015-07-08,13.220,13.470,13.200,13.365,11519077.0,1.537186e+08,14.902625,14.797600
2015-07-09,13.440,13.705,13.360,13.655,9765522.0,1.326167e+08,14.867688,14.803633
2015-07-10,14.000,14.365,13.850,14.325,12903451.0,1.829831e+08,14.843000,14.813000
2015-07-13,14.610,14.700,14.390,14.640,9412289.0,1.373634e+08,14.822750,14.823667

# Definition of strategy

In [72]:
def buy_condition(stock, row):
    date = None
    price = None
    status = None
    if np.isnan(row.SMA80) or np.isnan(row.SMA150):
        state = True
    else:
        state = row.SMA80 > row.SMA150
        if state == True:
            pos = stock.data.index.get_loc(row.Index)
            if pos + 1 == len(stock.data):
                price = None
                status = 'awaiting buy'
                date = row.Index
            else:
                next_row = stock.data.iloc[pos + 1]
                price = next_row.OPEN
                status = 'pending'
                date = next_row.name
    return {'state': state, 'date': date, 'price': price, 'status': status}

def sell_condition(stock, row, trade):
    date = None
    price = None
    status = None
    state = row.SMA80 < row.SMA150
    if state == True:
        pos = stock.data.index.get_loc(row.Index)
        if pos + 1 == len(stock.data):
            price = None
            status = 'awaiting sell'
            date = row.Index
        else:
            next_row = stock.data.iloc[pos + 1]
            price = next_row.OPEN
            status = 'closed'
            date = next_row.name
    return {'state': state, 'date': date, 'price': price, 'status': status}

In [73]:
SMA80_SMA150 = Strategy('SMA80_SMA150', buy_condition, sell_condition)

In [74]:
SMA80_SMA150.get_attributes()

name : SMA80_SMA150
type : Strategy
env : Environment: DEV
filename : Development/Strategy/SMA80_SMA150.p
folder : /Users/hugofayolle/Desktop/Bourse/Bourse_test/Data/
path : /Users/hugofayolle/Desktop/Bourse/Bourse_test/Data/Development/Strategy/SMA80_SMA150.p
creation_date : 2018-09-29 10:31:07
last_update : 2018-09-29 10:31:07
description :
buy_condition : <function buy_condition at 0x1113702f0>
sell_condition : <function sell_condition at 0x111370840>
trades : []
history : {}
last_status : {}

# Applying strategy

In [75]:
SMA80_SMA150.refresh([orange])

2014-02-14 00:00:00
pass
2014-10-10 00:00:00
closed
2014-12-04 00:00:00
pending
Trades for strategy SMA80_SMA150 successfully updated.

In [76]:
SMA80_SMA150.trades

[2014-12-05 00:00:00	2015-07-13 00:00:00	ORA	awaiting sell	14.32	14.64	2.153%]

In [21]:
orange.strategies

['SMA20_SMA50']

In [22]:
SMA20_SMA50.history

{'ORA': Timestamp('2018-09-21 00:00:00')}

In [23]:
SMA20_SMA50.last_status

{'ORA': 'closed'}

# Stock refresh with indicators

In [24]:
SMA20 = File('SMA20', "Indicator").load()
SMA50 = File('SMA50', "Indicator").load()

In [25]:
orange_test = Stock('ORA')

In [26]:
orange_test.refresh(to_date="2014-09-17")

ORA successfully updated!

In [27]:
orange_test.add_indicator(SMA20)
orange_test.add_indicator(SMA50)

In [28]:
orange_test.indicators

['SMA20', 'SMA50']

In [29]:
orange_test.refresh(to_date="2014-09-18")

ORA successfully updated!

In [30]:
orange_test.data

,CLOSE,HIGH,LOW,OPEN,SMA20,SMA50,TURNOVER,VOLUME
DATE,,,,,,,,
2014-02-14,9.231,9.237,9.143,9.200,NaN,NaN,5.056534e+07,5493685.0
2014-02-17,9.226,9.269,9.184,9.215,NaN,NaN,3.824005e+07,4143547.0
2014-02-18,9.303,9.321,9.221,9.224,NaN,NaN,7.937708e+07,8540213.0
2014-02-19,9.340,9.364,9.269,9.276,NaN,NaN,6.152310e+07,6594004.0
2014-02-20,9.384,9.384,9.233,9.250,NaN,NaN,5.633642e+07,6025974.0
2014-02-21,9.434,9.487,9.345,9.403,NaN,NaN,8.386507e+07,8894573.0
2014-02-24,9.613,9.648,9.373,9.378,NaN,NaN,7.792999e+07,8150488.0
2014-02-25,9.630,9.690,9.440,9.550,NaN,NaN,8.895996e+07,9295776.0
2014-02-26,9.305,9.623,9.252,9.603,NaN,NaN,1.703480e+08,18152477.0
2014-02-27,9.200,9.327,9.101,9.300,NaN,NaN,1.119747e+08,12172862.0
2014-02-28,9.069,9.200,9.030,9.173,NaN,NaN,1.309492e+08,14416002.0
2014-03-05,9.165,9.298,9.020,9.074,NaN,NaN,9.781073e+07,10647930.0
2014-03-06,10.130,10.235,9.440,9.500,NaN,NaN,4.753191e+08,47855850.0
2014-03-07,10.235,10.500,10.060,10.140,NaN,NaN,2.752481e+08,26751172.0
2014-03-10,10.675,10.715,10.240,10.240,NaN,NaN,2.144326e+08,20255363.0
2014-03-11,10.595,10.665,10.460,10.650,NaN,NaN,1.359032e+08,12841397.0
2014-03-12,10.555,10.585,10.455,10.505,NaN,NaN,1.138331e+08,10823248.0
2014-03-13,10.300,10.590,10.260,10.560,NaN,NaN,9.762179e+07,9396474.0
2014-03-14,10.115,10.205,9.700,10.165,NaN,NaN,2.360043e+08,23505993.0
2014-03-17,10.180,10.180,9.943,10.050,9.73425,NaN,8.309310e+07,8212576.0
2014-03-18,10.205,10.330,10.020,10.090,9.78295,NaN,8.334342e+07,8165304.0
2014-03-19,10.145,10.200,10.060,10.200,9.82890,NaN,8.251049e+07,8132717.0
2014-03-20,10.220,10.250,9.922,10.030,9.87475,NaN,1.538642e+08,15257210.0
2014-03-21,10.225,10.360,10.220,10.260,9.91900,NaN,1.823607e+08,17777684.0
2014-03-24,10.030,10.295,9.992,10.180,9.95130,NaN,8.183445e+07,8116514.0
2014-03-25,10.225,10.260,9.970,10.020,9.99085,NaN,8.866937e+07,8704683.0
2014-03-26,10.270,10.380,10.225,10.260,10.02370,NaN,6.312681e+07,6136637.0
2014-03-27,10.435,10.435,10.195,10.265,10.06395,NaN,9.450509e+07,9100609.0
2014-03-28,10.710,10.725,10.480,10.490,10.13420,NaN,9.796793e+07,9185692.0
2014-03-31,10.720,10.765,10.580,10.705,10.21020,NaN,7.454900e+07,6968061.0
...,...,...,...,...,...,...,...,...
2014-08-08,10.820,10.975,10.735,10.880,11.50875,11.7349,7.269891e+07,6705766.0
2014-08-11,11.055,11.085,10.805,10.900,11.49075,11.7154,7.844972e+07,7119875.0
2014-08-12,10.970,11.060,10.930,11.040,11.47500,11.6940,4.532000e+07,4122170.0
2014-08-13,11.115,11.235,11.040,11.055,11.45350,11.6774,5.751235e+07,5165929.0
2014-08-14,11.120,11.180,11.020,11.050,11.44200,11.6535,3.789731e+07,3414654.0
2014-08-15,11.050,11.315,11.015,11.135,11.42075,11.6227,6.022051e+07,5407609.0
2014-08-18,11.175,11.275,11.145,11.250,11.40925,11.5900,3.905671e+07,3490796.0
2014-08-19,11.190,11.265,11.160,11.200,11.38750,11.5612,3.189215e+07,2846791.0
2014-08-20,11.155,11.190,11.035,11.115,11.36475,11.5400,4.082357e+07,3669229.0
2014-08-21,11.365,11.365,11.130,11.170,11.34575,11.5198,5.295533e+07,4685639.0
2014-08-22,11.240,11.400,11.180,11.385,11.32600,11.4971,3.938101e+07,3497085.0
2014-08-25,11.480,11.480,11.315,11.375,11.30975,11.4835,5.851290e+07,5115395.0
2014-08-26,11.455,11.510,11.375,11.460,11.28150,11.4682,5.279947e+07,4612610.0
2014-08-27,11.615,11.660,11.420,11.420,11.26425,11.4553,5.447820e+07,4699402.0
2014-08-28,11.505,11.640,11.450,11.625,11.25200,11.4411,5.787670e+07,5027066.0
2014-08-29,11.520,11.565,11.370,11.550,11.25550,11.4347,4.955668e+07,4314812.0
2014-09-01,11.215,11.550,11.070,11.520,11.24175,11.4241,1.278301e+08,11411146.0
2014-09-02,11.090,11.220,10.990,11.210,11.22175,11.4103,1.203886e+08,10873408.0
2014-09-03,11.095,11.140,10.990,11.110,11.21100,11.3986,1.163035e+08,10488887.0
2014-09-04,11.210,11.330,11.000,11.040,11.22200,11.3885,1.089164e+08,9728866.0
2014-09-05,11.355,11.400,11.215,11.265,11.24875,11.3842,9.974275e+07,8792544.0
2014-09-08,11.460,11.510,11.340,11.355,11.26900,11.3829,6.512670e+07,5681538.0
2014-09-09,11.415,11.605,11.390,11.420,11.29125,11.3753,6.512042e+07,5671262.0
2014-09-10,11.465,11.495,11.385,11.395,11.30875,11.3770,4.607658e+07,4025056.0
2014-09-11,11.715,11.835,11.630,11.675,11.33850,11.3805,1.343730e+08,11460750.0
2014-09-12,11.670,11.790,11.600,11.775,11.36950,11.3849,6.183773e+07,5290859.0
2014-09-15,11.445,11.695,11.370,11.655,11.38300,11.3877,1.010101e+08,8785812.0
2014-09-16,11.290,11.380,11.150,11.300,11.38800,11.3898,1.093480e+08,9695980.0
2014-09-17,11.415,11.500,11.340,11.345,11.40100,11.3911,8.492666e+07,7430211.0
2014-09-18,11.515,11.545,11.460,11.495,11.40850,11.3965,6.600668e+07,5737886.0

# Awaiting_buy

In [31]:
orange_test = Stock('ORA')
orange_test.refresh(to_date="2014-09-17")
orange_test.add_indicator(SMA20)
orange_test.add_indicator(SMA50)

ORA successfully updated!

In [32]:
def buy_condition(stock, row, iterator):
    date = None
    price = None
    status = None
    if np.isnan(row.SMA20) or np.isnan(row.SMA50):
        state = True
    else:
        state = row.SMA20 > row.SMA50
        if state == True:
            try:
                row = iterator.__next__()
                price = row.OPEN
                status = 'pending'
                date = row.Index
            except Exception:
                price = None
                status = 'awaiting buy'
                date = row.Index
    return {'state': state, 'date': date, 'price': price, 'status': status}

def sell_condition(stock, row, trade, iterator):
    date = None
    price = None
    status = None
    state = row.SMA20 < row.SMA50
    if state == True:
        try:
            row = iterator.__next__()
            price = row.OPEN
            status = 'closed'
            date = row.Index
        except Exception:
            price = None
            status = 'awaiting sell'
            date = row.Index
    return {'state': state, 'date': date, 'price': price, 'status': status}

In [33]:
orange_test.indicators

['SMA20', 'SMA50']

In [34]:
test_SMA20_SMA50 = Strategy('SMA20_SMA50', buy_condition, sell_condition)

In [35]:
test_SMA20_SMA50.refresh([orange_test])

2014-02-14 00:00:00
2014-07-04 00:00:00
Trades for strategy SMA20_SMA50 successfully updated.

In [36]:
test_SMA20_SMA50

Strategy : SMA20_SMA50 (test)

In [37]:
test_SMA20_SMA50.trades

[2014-09-17 00:00:00	None			ORA	awaiting buy	None	None	 ]

In [38]:
orange_test.refresh(to_date="2014-09-18")

ORA successfully updated!

In [47]:
test_SMA20_SMA50.refresh([orange_test])

2014-09-17 00:00:00
Trades for strategy SMA20_SMA50 successfully updated.

In [48]:
test_SMA20_SMA50.trades

[2014-09-18 00:00:00	None			ORA	pending		11.495	11.515	0.094%]

# Awaiting sell

In [49]:
orange_test.refresh(to_date="2014-10-16")

ORA successfully updated!

In [50]:
test_SMA20_SMA50.refresh([orange_test])

2014-09-18 00:00:00
Trades for strategy SMA20_SMA50 successfully updated.

In [51]:
test_SMA20_SMA50.print_trades()

Name : SMA20_SMA50
Last refresh : 2018-09-22 20:23:45
OPENING_DATE		CLOSING_DATE		STOCK	STATUS		BID	LAST	PERF
2014-09-18 00:00:00	2014-10-16 00:00:00	ORA	awaiting sell	11.495	10.52	-8.555%

In [52]:
orange_test.refresh(to_date="2014-10-17")

ORA successfully updated!

In [53]:
test_SMA20_SMA50.refresh([orange_test])

2014-10-16 00:00:00
2014-10-16 00:00:00
Trades for strategy SMA20_SMA50 successfully updated.

In [54]:
test_SMA20_SMA50.print_trades()

Name : SMA20_SMA50
Last refresh : 2018-09-22 20:23:55
OPENING_DATE		CLOSING_DATE		STOCK	STATUS		BID	LAST	PERF
2014-09-18 00:00:00	2014-10-17 00:00:00	ORA	closed		11.495	10.505	-8.686%

In [55]:
SMA20_SMA50 = File('SMA20_SMA50', "Strategy").load()

In [56]:
SMA20_SMA50

Strategy : SMA20_SMA50 (test)

In [57]:
orange_test.refresh()

ORA successfully updated!

In [58]:
test_SMA20_SMA50.refresh([orange_test])

2014-10-17 00:00:00
2014-11-11 00:00:00
2015-03-24 00:00:00
2015-03-24 00:00:00
2015-07-23 00:00:00
2015-08-31 00:00:00
2015-08-31 00:00:00
2015-10-23 00:00:00
2015-12-21 00:00:00
2015-12-21 00:00:00
2016-02-02 00:00:00
2016-03-02 00:00:00
2016-03-02 00:00:00
2016-03-04 00:00:00
2016-04-05 00:00:00
2016-04-05 00:00:00
2016-05-31 00:00:00
2016-06-24 00:00:00
2016-06-24 00:00:00
2016-10-12 00:00:00
2016-11-24 00:00:00
2016-11-24 00:00:00
2017-01-02 00:00:00
2017-02-20 00:00:00
2017-02-20 00:00:00
2017-03-22 00:00:00
2017-04-19 00:00:00
2017-04-19 00:00:00
2017-05-15 00:00:00
2017-06-27 00:00:00
2017-06-27 00:00:00
2017-08-21 00:00:00
2017-09-05 00:00:00
2017-09-05 00:00:00
2017-11-08 00:00:00
2018-02-06 00:00:00
2018-02-06 00:00:00
2018-04-12 00:00:00
2018-06-19 00:00:00
2018-06-19 00:00:00
Trades for strategy SMA20_SMA50 successfully updated.

In [59]:
test_SMA20_SMA50.trades

[2014-09-18 00:00:00	2014-10-17 00:00:00	ORA	closed		11.495	10.505	-8.686%,
 2014-11-12 00:00:00	2015-03-26 00:00:00	ORA	closed		12.98	15.0	15.47%,
 2015-07-24 00:00:00	2015-09-01 00:00:00	ORA	closed		15.265	13.88	-9.146%,
 2015-10-26 00:00:00	2015-12-22 00:00:00	ORA	closed		15.93	15.25	-4.345%,
 2016-02-03 00:00:00	2016-03-03 00:00:00	ORA	closed		16.17	16.025	-0.976%,
 2016-03-07 00:00:00	2016-04-06 00:00:00	ORA	closed		15.835	14.115	-10.933%,
 2016-06-01 00:00:00	2016-06-27 00:00:00	ORA	closed		15.555	13.5	-13.281%,
 2016-10-13 00:00:00	2016-11-25 00:00:00	ORA	closed		13.64	13.72	0.506%,
 2017-01-03 00:00:00	2017-02-21 00:00:00	ORA	closed		14.625	14.51	-0.866%,
 2017-03-23 00:00:00	2017-04-20 00:00:00	ORA	closed		14.795	14.015	-5.348%,
 2017-05-16 00:00:00	2017-06-28 00:00:00	ORA	closed		15.33	14.2	-7.445%,
 2017-08-22 00:00:00	2017-09-06 00:00:00	ORA	closed		14.21	13.9	-2.26%,
 2017-11-09 00:00:00	2018-02-07 00:00:00	ORA	closed		14.345	13.745	-4.259%,
 2018-04-13 00:00:00	2018-06-20 00:00:00	ORA	closed		14.18	14.515	2.281%]

# Pass

In [43]:
umi = Stock('UMI')
umi.refresh(to_date="2018-09-21")
umi.add_indicator(SMA80)
umi.add_indicator(SMA150)

UMI successfully updated!

In [44]:
umi.data

,OPEN,HIGH,LOW,CLOSE,VOLUME,TURNOVER,SMA20,SMA50
DATE,,,,,,,,
2017-10-16,37.880,38.690,37.730,37.940,718341.0,2.742650e+07,NaN,NaN
2017-10-17,38.650,39.000,37.955,38.695,875228.0,3.363746e+07,NaN,NaN
2017-10-18,38.590,38.600,37.775,37.785,765665.0,2.914730e+07,NaN,NaN
2017-10-19,37.800,37.805,37.390,37.715,734551.0,2.763320e+07,NaN,NaN
2017-10-20,37.680,37.715,36.935,37.670,803936.0,3.016239e+07,NaN,NaN
2017-10-23,37.675,37.925,37.350,37.800,490272.0,1.849056e+07,NaN,NaN
2017-10-24,37.685,37.695,37.235,37.415,538988.0,2.017627e+07,NaN,NaN
2017-10-25,37.280,37.900,37.085,37.685,533810.0,2.003121e+07,NaN,NaN
2017-10-26,37.600,38.740,37.550,38.700,661577.0,2.531232e+07,NaN,NaN
2017-10-27,38.800,38.815,38.170,38.250,590292.0,2.262468e+07,NaN,NaN
2017-10-30,38.200,38.200,37.515,37.965,650821.0,2.469410e+07,NaN,NaN
2017-10-31,37.930,38.580,37.710,38.370,491239.0,1.877317e+07,NaN,NaN
2017-11-01,38.165,38.735,38.165,38.505,555406.0,2.140044e+07,NaN,NaN
2017-11-03,38.795,39.725,38.155,39.700,891585.0,3.500616e+07,NaN,NaN
2017-11-06,39.700,39.745,38.815,38.950,709692.0,2.763213e+07,NaN,NaN
2017-11-07,38.880,39.235,38.565,39.080,725869.0,2.823319e+07,NaN,NaN
2017-11-08,39.000,39.435,38.655,38.740,765935.0,2.983215e+07,NaN,NaN
2017-11-09,38.670,38.800,37.545,37.940,1092471.0,4.149386e+07,NaN,NaN
2017-11-10,37.580,38.275,37.480,38.155,627365.0,2.381477e+07,NaN,NaN
2017-11-13,38.200,38.255,37.220,37.425,597414.0,2.224591e+07,NaN,NaN
2017-11-14,37.425,37.980,37.130,37.270,396540.0,1.485338e+07,NaN,NaN
2017-11-15,37.065,37.520,36.400,37.420,686311.0,2.549503e+07,NaN,NaN
2017-11-16,37.595,38.440,37.535,38.365,649861.0,2.480185e+07,NaN,NaN
2017-11-17,38.340,38.555,37.945,38.500,559921.0,2.148853e+07,NaN,NaN
2017-11-20,38.300,38.740,38.225,38.710,504465.0,1.946669e+07,NaN,NaN
2017-11-21,38.610,39.750,38.330,39.275,761149.0,2.987114e+07,NaN,NaN
2017-11-22,39.320,39.400,38.375,38.380,410005.0,1.588137e+07,NaN,NaN
2017-11-23,38.185,39.195,37.930,38.695,712919.0,2.758466e+07,NaN,NaN
2017-11-24,38.735,39.350,38.480,39.240,439621.0,1.719954e+07,NaN,NaN
2017-11-27,39.110,39.295,38.845,39.085,370623.0,1.448993e+07,NaN,NaN
...,...,...,...,...,...,...,...,...
2018-08-13,48.370,48.990,48.090,48.570,580613.0,2.819806e+07,49.187375,46.785033
2018-08-14,48.660,49.120,48.440,48.590,489866.0,2.383942e+07,49.257500,46.816667
2018-08-15,48.690,48.770,46.260,46.350,995896.0,4.677989e+07,49.298000,46.824967
2018-08-16,46.540,46.550,45.400,45.810,1189422.0,5.454562e+07,49.339750,46.828600
2018-08-17,45.920,46.300,45.670,46.180,716391.0,3.299343e+07,49.338875,46.843300
2018-08-20,46.510,47.010,46.250,46.370,588869.0,2.740716e+07,49.340875,46.864433
2018-08-21,46.390,46.580,45.940,46.450,553901.0,2.567225e+07,49.343250,46.887533
2018-08-22,46.380,47.200,46.190,47.050,775787.0,3.639442e+07,49.343875,46.916300
2018-08-23,47.800,48.400,47.150,47.170,697550.0,3.316163e+07,49.348625,46.944833
2018-08-24,46.970,47.600,46.810,47.600,681772.0,3.229185e+07,49.359125,46.977833
2018-08-27,47.850,48.560,47.700,48.350,496489.0,2.392812e+07,49.369125,47.011367
2018-08-28,48.500,49.020,48.410,48.600,430643.0,2.094956e+07,49.382125,47.044067
2018-08-29,48.610,48.920,48.460,48.700,375649.0,1.828938e+07,49.394625,47.076367
2018-08-30,48.680,48.810,48.270,48.690,375124.0,1.822969e+07,49.404500,47.109133
2018-08-31,48.600,48.600,47.390,48.040,520726.0,3.259922e+07,49.405125,47.142733
2018-09-03,48.000,48.270,47.830,48.150,372546.0,1.790629e+07,49.409625,47.181333
2018-09-04,48.270,48.340,46.920,47.250,598016.0,2.832415e+07,49.400000,47.213033
2018-09-05,47.070,47.080,46.100,46.170,707061.0,3.281888e+07,49.372125,47.249067
2018-09-06,46.000,46.320,45.570,45.750,934793.0,4.287464e+07,49.331500,47.283133
2018-09-07,45.710,46.090,45.360,45.880,746975.0,3.417317e+07,49.293500,47.321767
2018-09-10,45.970,46.210,45.640,46.080,594730.0,2.735290e+07,49.253000,47.350267
2018-09-11,46.290,46.420,45.700,46.140,511881.0,2.358901e+07,49.216375,47.385200
2018-09-12,46.150,47.010,46.010,46.340,642938.0,2.981148e+07,49.188625,47.400267
2018-09-13,46.520,47.130,46.210,46.760,495756.0,2.319735e+07,49.174125,47.400133
2018-09-14,46.840,48.080,46.840,47.840,659345.0,3.140326e+07,49.173500,47.404400
2018-09-17,47.630,47.780,46.940,47.760,516405.0,2.456466e+07,49.169000,47.416467
2018-09-18,47.860,48.550,47.760,48.180,557231.0,2.684646e+07,49.179000,47.423133
2018-09-19,48.670,49.360,48.250,49.130,826077.0,4.045902e+07,49.177000,47.436800
2018-09-20,49.200,50.180,49.120,50.160,795281.0,3.971162e+07,49.199000,47.464000
2018-09-21,50.500,50.780,50.000,50.020,1147333.0,5.754641e+07,49.204375,47.490133